apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
  labels:
    name: myapp
spec:
  containers:
  - name: docker
    image: docker
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
          path: /var/run/docker.sock
          type: Socket
