apiVersion: v1
kind: Pod
metadata:
  name: myapp-volume
  labels:
    name: myapp-volume
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
      - containerPort: 80
  - name: html-udater
    image: alpine
    command: ["/bin/sh" , "-c"]
    args:
      - while true; do date >> /html/index.html;sleep 10; done
    resources:
        limits:
          memory: "50Mi"
          cpu: "100m"
    volumeMounts:
      - name: html
        mountPath: /html
  volumes:
    - name: html
      emptyDir: {}